### ISSUE TITLE
Question to understand the receiving loop

### ISSUE THREAD

**Issue by Tochemey** [arschles/gotp#8]
Hello @arschles ,

First and foremost great work on this piece of code. I know you are quite busy. Per chance you come back to this repo I would like you to educate me on the receiving loop https://github.com/arschles/gotp/blob/master/actor.go#L104.

Thanks

**Comment by arschles** [comment]
wow, I'm surprised anybody is interested in this repo! @Tochemey I'm happy you're here. I should first mention that I don't have much time to support it (I'll write that on the README too) but I am more than happy to explain the receiving loop, from what I can remember at least.

do you have any specific questions on it?

**Comment by Tochemey** [comment]
Thanks @arschles for the reply. I thought you will not reply 🤣. We are working on an actor framework and I came across this beautiful work. I have QAed it and it is pretty cool. Just that the receiving loop was a bit weird for me to understand.
Yeah you may say why building an actor framework instead of using ProtoActor. Honestly proto actor is relying on gogo protobuf and I think with golang we can make an actor framework very simple.

**Comment by arschles** [comment]
Got it. Thanks, I'm glad this is working well for you. Are you looking for a general overview of this code?

**Comment by Tochemey** [comment]
@arschles I totally understand the code base looking at my erlang and akka background. Thank you

**Comment by Tochemey** [comment]
@arschles I would love to have some pointers on how we can implement clustering and co. Once we have that I think this will be a great framework. I am willing to help.

**Comment by arschles** [comment]
@Tochemey I haven't given any thought on implementing clustering. What are the features that would be required for that?

**Comment by Tochemey** [comment]
Hello @arschles, thank you for asking for feature. I would like to know whether this project is something you really want to move forward and make it a fully-fledged actor framework for golang using some of the erlang concept.

**Comment by arschles** [comment]
@Tochemey I would love to, but I unfortunately don't have time to spend on doing that work.

**Comment by Tochemey** [comment]
@arschles I understand

**Comment by Tochemey** [comment]
@arschles You inspired me to put up this work. https://github.com/Tochemey/goakt. Any feedback will be welcome. I know you are busy though
